apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app-lanchonete
  ports:
    - port: 8080 # Porta externa do pod
      targetPort: 8080 # Porta interna do pod
  type: LoadBalancer
