apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.34.1
          imagePullPolicy: IfNotPresent
          command:
            [
              "sh",
              "-c",
              'until nc -z mysql-service 3306; do echo "Aguardando banco de dados..."; sleep 5; done;',
            ]
      containers:
        - name: app-deployment
          image: app-lanchonete:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  key: DATASOURCE_DRIVER_CLASS_NAME
                  name: env-config
            - name: DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DATASOURCE_PASSWORD
                  name: env-config
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATASOURCE_URL
                  name: env-config
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DATASOURCE_USERNAME
                  name: env-config
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: env-config
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: env-config
            - name: MYSQL_ROOT_HOST
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_HOST
                  name: env-config
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: env-config
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: env-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "400m"
            limits:
              memory: "1Gi"
              cpu: "800m"
          startupProbe:
            httpGet:
              path: /startup
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 6
            failureThreshold: 50
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 6
            failureThreshold: 50
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 6
            failureThreshold: 50
