apiVersion: v1
kind: Service
metadata:
  name: app
  annotations:
    # IP externo fixo para o serviço (LoadBalancer)
    metallb.universe.tf/loadBalancerIPs: "192.168.100.100"
spec:
  selector:
    app: app
  ports:
    - port: 8080 # Porta externa do pod
      targetPort: 8080 # Porta interna do pod
  type: LoadBalancer
