apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-lanchonete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bd-lanchonete
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bd-lanchonete
    spec:
      initContainers:
        - name: init-mysql
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until [ -e /var/lib/mysql ]; do echo esperando pelo volume de dados; sleep 2; done",
            ]
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: dados-lanchonete
      containers:
        - args:
            - mysqld
          env:
            - name: DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  key: DATASOURCE_DRIVER_CLASS_NAME
                  name: env
            - name: DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DATASOURCE_PASSWORD
                  name: env
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATASOURCE_URL
                  name: env
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DATASOURCE_USERNAME
                  name: env
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: env
            - name: MYSQL_ROOT_HOST
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_HOST
                  name: env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: env
          image: efrancodelima/bd-lanchonete:latest
          name: bd-lanchonete
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: dados-lanchonete
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
      volumes:
        - name: dados-lanchonete
          persistentVolumeClaim:
            claimName: dados-lanchonete
