apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: bd-lanchonete
  name: bd-lanchonete
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bd-lanchonete
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: bd-lanchonete
    spec:
      containers:
        - args:
            - mysqld
          env:
            - name: DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  key: DATASOURCE_DRIVER_CLASS_NAME
                  name: env
            - name: DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DATASOURCE_PASSWORD
                  name: env
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATASOURCE_URL
                  name: env
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DATASOURCE_USERNAME
                  name: env
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: env
            - name: MYSQL_ROOT_HOST
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_HOST
                  name: env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: env
          image: mysql:8.4.0
          name: bd-lanchonete
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: dados-lanchonete
      restartPolicy: Always
      volumes:
        - name: dados-lanchonete
          persistentVolumeClaim:
            claimName: dados-lanchonete
