apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: dados-lanchonete
  name: dados-lanchonete
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
