apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-server-config
  namespace: kube-system
data:
  metrics-server-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://kubernetes.default.svc
      name: local
    contexts:
    - context:
        cluster: local
        user: metrics-server
      name: metrics-server-context
    current-context: metrics-server-context
    users:
    - name: metrics-server
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
