apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306 # Porta externa do pod
      targetPort: 3306 # Porta interna do pod
  type: ClusterIP
